const int COMMAND_L_WHEEL_FORWARD = 0;
const int COMMAND_L_WHEEL_FORWARD_S = 1;
const int COMMAND_L_WHEEL_BACKWARD = 2;
const int COMMAND_L_WHEEL_BACKWARD_S = 3;
const int COMMAND_R_WHEEL_FORWARD = 4;
const int COMMAND_R_WHEEL_FORWARD_S = 5;
const int COMMAND_R_WHEEL_BACKWARD = 6;
const int COMMAND_R_WHEEL_BACKWARD_S = 7;